server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: robot_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: robot_logs
          __path__: /var/log/robot.log

    pipeline_stages:
      - json:
          expressions:
            observed_timestamp_rfc3339: observed_timestamp_rfc3339
            instrumentation_scope: instrumentation_scope
            severity_text: severity_text
      - labels:
          observed_timestamp_rfc3339:
          instrumentation_scope:
          severity_text:
